/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as CheatsheetRouteImport } from './routes/cheatsheet'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogsIndexRouteImport } from './routes/logs.index'
import { Route as LogsSlugRouteImport } from './routes/logs.$slug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetRoute = CheatsheetRouteImport.update({
  id: '/cheatsheet',
  path: '/cheatsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsSlugRoute = LogsSlugRouteImport.update({
  id: '/logs/$slug',
  path: '/logs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/stats': typeof StatsRoute
  '/tools': typeof ToolsRoute
  '/logs/$slug': typeof LogsSlugRoute
  '/logs/': typeof LogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/stats': typeof StatsRoute
  '/tools': typeof ToolsRoute
  '/logs/$slug': typeof LogsSlugRoute
  '/logs': typeof LogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/stats': typeof StatsRoute
  '/tools': typeof ToolsRoute
  '/logs/$slug': typeof LogsSlugRoute
  '/logs/': typeof LogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cheatsheet'
    | '/stats'
    | '/tools'
    | '/logs/$slug'
    | '/logs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cheatsheet'
    | '/stats'
    | '/tools'
    | '/logs/$slug'
    | '/logs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cheatsheet'
    | '/stats'
    | '/tools'
    | '/logs/$slug'
    | '/logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheatsheetRoute: typeof CheatsheetRoute
  StatsRoute: typeof StatsRoute
  ToolsRoute: typeof ToolsRoute
  LogsSlugRoute: typeof LogsSlugRoute
  LogsIndexRoute: typeof LogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheet': {
      id: '/cheatsheet'
      path: '/cheatsheet'
      fullPath: '/cheatsheet'
      preLoaderRoute: typeof CheatsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$slug': {
      id: '/logs/$slug'
      path: '/logs/$slug'
      fullPath: '/logs/$slug'
      preLoaderRoute: typeof LogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheatsheetRoute: CheatsheetRoute,
  StatsRoute: StatsRoute,
  ToolsRoute: ToolsRoute,
  LogsSlugRoute: LogsSlugRoute,
  LogsIndexRoute: LogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
